[package]
name = "practice-tool-core-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = [
  "Win32_System_Registry",
  "Win32_UI",
  "Win32_UI_Shell",
  "Win32_UI_Controls",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Com",
] }
