[package]
name = "practice-tool-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.11.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"

[dev-dependencies]
imgui-wgpu = "0.24.0"
pollster = "0.3.0"
tempfile = "3.10.1"
wgpu = "0.17.2"
winit = "0.27.5"

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = false
