[package]
name = "practice-tool-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hudhook = "0.6.1"
imgui = "0.11.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
