[package]
name = "practice-tool-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.11.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"

[dev-dependencies]
glow = "0.12.0"
imgui-glow-renderer = "0.11.0"
imgui-sdl2-support = "0.11.0"
sdl2 = { version = "0.34.5" }
tempfile = "3.10.1"

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = false
