[package]
name = "practice-tool-memedit"
version = "0.1.0"
edition = "2021"

[dependencies]
practice-tool-core = { path = ".." }
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Threading",
] }

[dev-dependencies]
windows = { workspace = true, features = ["Win32_System_Memory", "Win32_System_SystemServices"] }

[build-dependencies]
cc = "1.2"
